// FR/EN switch shared by the 3D pages. Needs a global DICT = [[french innerHTML, english], ...] defined before.
// Static text is translated in place (and restored from the original); text generated by the page uses tr(fr, en).
let LANG = "fr";
try {
  const q = new URLSearchParams(location.search).get("lang"), s = localStorage.getItem("lang");
  LANG = q || s || ((navigator.language || "fr").slice(0, 2) === "fr" ? "fr" : "en");
} catch (e) { }
if (LANG !== "en") LANG = "fr";
const tr = (fr, en) => LANG === "en" ? en : fr;
const norm = s => s.replace(/\s+/g, " ").trim();
const DMAP = new Map(DICT.map(([f, e]) => [norm(f), e]));
const TITLES = { fr: document.title, en: typeof TITLE_EN === "string" ? TITLE_EN : document.title };
function xlate(root) {
  const en = LANG === "en", texts = [];
  const tw = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  while (tw.nextNode()) texts.push(tw.currentNode);
  if (!en) texts.forEach(n => { if (n.__fr !== undefined) { n.nodeValue = n.__fr; n.__fr = undefined; } });
  root.querySelectorAll("*").forEach(el => {
    if (!en) { if (el.__fr !== undefined) { el.innerHTML = el.__fr; el.__fr = undefined; } return; }
    if (el.__fr !== undefined || el.querySelector("input,select,canvas,button,table")) return;
    const k = norm(el.innerHTML);
    if (DMAP.has(k)) { el.__fr = el.innerHTML; el.innerHTML = DMAP.get(k); }
  });
  if (en) {
    const tw2 = document.createTreeWalker(root, NodeFilter.SHOW_TEXT), t2 = [];
    while (tw2.nextNode()) t2.push(tw2.currentNode);
    t2.forEach(n => {
      const v = n.nodeValue, k = norm(v);
      if (k && n.__fr === undefined && DMAP.has(k)) { n.__fr = v; n.nodeValue = /^\s*/.exec(v)[0] + DMAP.get(k) + /\s*$/.exec(v)[0]; }
    });
  }
}
function setLang(l, save) {
  LANG = l === "en" ? "en" : "fr";
  if (save) { try { localStorage.setItem("lang", LANG); } catch (e) { } }
  document.documentElement.lang = LANG; document.title = TITLES[LANG];
  ["side", "parts"].forEach(id => { const r = document.getElementById(id); if (r) xlate(r); });
  document.querySelectorAll("#lang button").forEach(b => b.classList.toggle("on", b.dataset.l === LANG));
  if (typeof onLang === "function") onLang();
}
document.querySelectorAll("#lang button").forEach(b => b.addEventListener("click", () => setLang(b.dataset.l, true)));
