import os
here = os.path.dirname(os.path.abspath(__file__))
vendor = os.path.join(here, "vendor")
rd = lambda p: open(p, encoding="utf8").read()
safe = lambda s: s.replace("</script", "<\\/script")
html = rd(os.path.join(here, "page_template.tpl"))
html = (html.replace("__THREE__", safe(rd(os.path.join(vendor, "three.min.js"))))
            .replace("__ORBIT__", safe(rd(os.path.join(vendor, "OrbitControls.js"))))
            .replace("__ROOMENV__", safe(rd(os.path.join(vendor, "RoomEnvironment.js"))))
            .replace("__I18N__", safe(rd(os.path.join(here, "i18n.js"))))
            .replace("__OPTICS__", safe(rd(os.path.join(here, "optics.js"))))
            .replace("__DATA__", rd(os.path.join(here, "meshes.json"))))
out = os.path.join(here, "oculaire_3D.html")
open(out, "w", encoding="utf8").write(html)
print("ecrit oculaire_3D.html : %.1f Mo" % (os.path.getsize(out) / 1e6))
